# ---- Подключение к БД PostgreSQL ----
spring.datasource.url=jdbc:postgresql://localhost:5432/hogwarts
spring.datasource.username=student
spring.datasource.password=chocolatefrog

# ---- Liquibase ----
# Путь к мастер-файлу миграций
spring.liquibase.change-log=classpath:liquibase/changelog-master.yml

# ---- JPA / Hibernate ----
# Схему создаёт и изменяет только Liquibase.
# Hibernate только проверяет соответствие сущностей и таблиц.
spring.jpa.hibernate.ddl-auto=validate
//test
# Логирование SQL (опционально)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect